apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: n8n-https-redirect
  namespace: n8n
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
