apiVersion: v1        # versión de la API de Kubernetes
kind: ConfigMap       # tipo de objeto
metadata:
  name: app-config    # nombre del ConfigMap
  namespace: produccion  # en qué namespace vive
data:
  APP_ENV: "production"     # ambiente
  APP_COLOR: "red"          # color para identificar el ambiente visualmente
  APP_DEBUG: "false"          # mostrar errores detallados